concatenated_receptors_file: /doctorai/skanduri/ligo_usecase/run3/witnessrate_0.001/inst1/exported_dataset/airr/concatenated_flat_receptor_file.tsv
label_field: "epitope"
k: 3
num_processes: 50
group_field: "repertoire_id"
n_splits: 5
pval_threshold: 0.001
output_path: /doctorai/skanduri/ligo_usecase/run3/mil_witnessrate_0.001